config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'
  end
  ActiveAdmin.routes(self)
  mount ActionCable.server, at: '/cable'

  root to: 'home#index'

  # Used for password reset
  resources :passwords, controller: 'passwords', only: [:create, :new, :edit, :update]
  # Used for `session_path` for login helper
  resource :session, controller: 'sessions', only: [:create]

  # Seemingly still used for some user changes
  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit]
    resource :password, controller: 'passwords', only: [:update]
  end

  get '/sign_in' => 'sessions#new'
  match '/sign_out' => 'sessions#destroy', via: [:get, :delete]
  get '/sign_up' => 'users#new'
  get '/signup' => 'users#new_alternative'
  get '/confirm_email/:token' => 'email_confirmations#update', as: 'confirm_email'
  get '/resend_verification_instructions' => 'email_confirmations#create'
  get '/subscriptions' => 'subscriptions#show'
  post '/subscriptions/webhooks' => 'subscriptions#webhook'
  get '/account' => 'accounts#show'
  get '/pages/*id' => 'pages#show', as: :page, format: false
  get 'admin' => 'admin#index'
  get '/landing' => 'users#new'

  namespace :families, path: 'communities' do
    resources :ownership_transfers, only: [:show, :update] do
      get :decline_invitation, on: :member
    end
  end

  namespace :vaults do
    get ':vault_id/download', to: 'downloads#show'
  end
  namespace :publications do
    get ':publication_id/download', to: 'downloads#show'
  end

  resources :users, only: [:new, :create, :update] do
    collection do
      delete :destroy
    end
  end

  resources :invitations, only: [] do
    get :decline, on: :member
  end

  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'sign_in#create'
      post '/sign_up' => 'sign_up#create'
      resource :ownership_transfer, only: [:new, :create]
      resources :categories, only: [:index]

      resources :vaults, only: [:index, :show] do
        scope module: :vaults do
          resources :boxes, only: [:show, :create, :update]
          resource :items, only: [:destroy]
          resources :items, only: [:index]
        end
        resources :attachments, only: [:create, :update], controller: 'vaults/attachments' do
          collection do
            post :move
            post :copy
          end
        end
      end

      namespace :messages do
        resources :recipients, only: [:index]
      end
      namespace :billing do
        post '/invoice_status_changed', to: 'callbacks#invoice_status_changed'
        post '/store_any_event', to: 'callbacks#store_any_event'
      end

      resources :kinships, only: [:show, :update, :destroy] do
        get '/by_family/:family_id' => 'kinships#show_by_family', on: :collection
        get '/kinship_data' => 'kinships#kinship_data', on: :collection
        post :notify, on: :member
        scope module: :kinships do
          resource :role, only: [:update]
          resource :offline_member, only: [:update]
          resource :invitation, only: [:create]
        end
      end

      resources :received_invitations, only: [:index]
      resources :invitations, only: [:show, :update]
      resource :invitations, only: [:destroy] do
        scope module: :invitations do
          resource :resend, only: [:create]
        end
      end

      resources :followers, only: [:index]
      resources :followings, only: [:index, :show, :destroy]
      resources :families, only: [:index, :update, :show, :create, :destroy] do
        get :quick_list, on: :collection

        scope module: :families do
          resources :kinships, only: [:index]
          resources :offline_members, only: [:create, :update]
          resources :invitations, only: [:index, :create]
        end
      end
      resources :appreciations, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resources :chapters, only: [:index, :create, :destroy, :update]
      get '/table_content_list', to: 'chapters#table_content_list'

      resources :publications, only: [:index, :show, :create, :destroy] do
        scope module: :publications do
          resources :sections, only: [:index, :create, :update, :destroy]
          resources :families, only: [:index]
          resource :story, only: [:create, :update, :destroy] do
            member do
              post :duplicate
              post :notify
              get :chapter_links
            end
          end
        end
      end

      resource :story, only: [:create]

      resources :requests, only: [:create]
      resource :user, only: [:update]
    end
  end

  get '/*path', to: 'vue#show',
                format: false,
                constraints: ->(req) do
                  req.path.exclude? 'rails/active_storage'
                end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include VueRoutesHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Temp. remove payment feature
  # before_action :require_subscription
  before_action :add_www_subdomain
  before_action :require_login

  helper_method :current_user?

  rescue_from ActiveRecord::RecordNotFound, with: :sign_in_with_other
  rescue_from CanCan::AccessDenied, with: :sign_in_with_other

  private

  def access_denied(_)
    redirect_to root_path
  end

  def url_after_denied_access_when_signed_out
    if request.original_fullpath.include?('/invitations/')
      cookies[:invitation_id] = request.original_fullpath.split('/').last
    end
    sign_in_url
  end

  def current_user
    super || Guest.new
  end

  def current_user?(user)
    user == current_user
  end

  def ensure_subscription_active
    return if family.active?

    redirect_to "/communities/#{family.id}/kinships",
                alert: t('flashes.alert.paused_subscription')
  end

  def sign_in_with_other
    redirect_to root_url, notice: t('flashes.sign_in_with_other')
  end

  def require_subscription
    return unless ENV['RENEW_SUBSCRIPTION'] == 'true'
    return unless signed_in?
    return if current_user.subscription

    sign_out
  end

  def add_www_subdomain
    return unless Rails.env.production?
    return if /^www/.match?(request.host)

    redirect_to(
      request.url.gsub(request.protocol, "#{request.protocol}www."),
      status: 301
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_image_css(url)
    url.blank? ? '' : "background-image: url(#{url});"
  end
end

app/views/application/_analytics.html.slim
- if Global.analytics.mixpanel.enabled?
  javascript:
    (function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
    0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
    for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
    mixpanel.init('#{Global.analytics.mixpanel.key}');

- if ENV['GTM_KEY'].blank?
  - if Global.analytics.adwords.enabled? || Global.analytics.ga.enabled?
    script(async src='https://www.googletagmanager.com/gtag/js?id=#{Global.analytics.adwords.key || Global.analytics.ga.key}')
    javascript:
      window.dataLayer = window.dataLayer || []
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date())

      const adWordsKey =  '#{Global.analytics.adwords.key}'
      const gaKey =  '#{Global.analytics.ga.key}'
      if (adWordsKey.length) gtag('config', adWordsKey)
      if (gaKey.length) gtag('config', gaKey)

<!--- Begin GTM --->
- if Global.analytics.gtm.enabled? && ENV['GTM_KEY'].present?
  - if Rails.env.production?
    <!--- GTM production --->
    javascript:
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','#{Global.analytics.gtm.key}')

  - elsif Rails.env.staging?
    <!--- GTM staging --->
    javascript:
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=h9PPGNRjfFEIAioshjuFFg&gtm_preview=env-6&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','#{Global.analytics.gtm.key}')

  - elsif Rails.env.development?
    <!--- GTM development --->
    javascript:
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=rko14NUA8FBH32TB2bcEMg&gtm_preview=env-8&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','#{Global.analytics.gtm.key}')

  - else
    <!--- GTM disabled or key missing --->

<!--- end GTM --->

app/views/application/_apiary_analytics.html.slim
<!--- Begin Apiary GA --->
noscript
  iframe src="https://www.googletagmanager.com/ns.html?id=#{ENV['GA_KEY_APIARY']}" height="0" width="0" style="display:none;visibility:hidden"
javascript:
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer',"#{ENV['GA_KEY_APIARY']}");
<!--- end Apiary GA --->

app/views/application/_conversion_tracking_script.slim
/! Google Code for kinescope registrations Conversion Page
javascript:
  /* <![CDATA[ */
  var google_conversion_id = 1072725388;
  var google_conversion_language = "en";
  var google_conversion_format = "3";
  var google_conversion_color = "ffffff";
  var google_conversion_label = "93TqCJXkw3UQjPvB_wM";
  var google_remarketing_only = false;
/* ]]> */
script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript"
noscript
  div style="display:inline;"
    img alt="" height="1" src="//www.googleadservices.com/pagead/conversion/1072725388/?label=93TqCJXkw3UQjPvB_wM&guid=ON&script=0" style="border-style:none;" width="1" /

app/views/application/_footer.html.slim
.footer-spacer

footer.footer
  .logo
    = image_tag('logo.svg')

  ul.links
    li
      = link_to "Terms of Use", '/terms-of-use/'
    li
      = link_to "Privacy Policy", '/privacy-policy/'
    li
      / = link_to "Help Center", 'https://help.kinscape.com', target: "_blank"
      = link_to "Help Center", 'https://intercom.help/kinscape', target: "_blank"

  .copyright
    = "&copy;Kinscape, LLC ".html_safe + Time.now.year.to_s + ". All Rights Reserved."

app/views/application/_global_nav.html.slim
nav#slide-menu
  .inner-wrapper
    = link_to '#', class: 'close', 'ng-click' => 'menu.toggle()' do
      i.fa.fa-times

    ul.user-info
      li
        = link_to stories_path(user: current_user.id), class: 'name' do
          = current_user.name
        .email = current_user.email

    ul.main-links.flexible
      - unless current_user.guest?
        li
          = link_to stories_path, method: :post, title: t('stories.new_title') do
            i.fa.fa-pencil
            span = t('stories.new')

      li
        = link_to stories_path, title: t('header.stories_title') do
          i.fa.fa-book
          span = t('header.stories')

      li
        = link_to families_path, title: t('header.families_title'), class: params[:controller] == 'families' ? 'selected' : '' do
          i.fa.fa-users
          span = t('header.families')

      li
        = link_to mylife_profile_path, title: t('header.mylife_title'), class: params[:controller] == 'mylife/profile' ? 'selected' : '' do
          i.fa.fa-user
          span = t('header.mylife')

      li
        = link_to '/vaults', title: t('header.vault_title'), class: params[:controller] == 'vaults' ? 'selected' : '' do
          i.fa.fa-archive
          span = t('header.vault')

      - unless current_user.guest?
        li.menu-item
          menu-item(:user="#{current_user_serialize(@user) || 'undefined'}":current-user="#{current_user_serialize(current_user)}" portal-id="" )
            i.fa.fa-send
            span = t('header.message')

      li.divider

    ul.main-links
      li
        = link_to mylife_profile_path do
          i.fa.fa-cog
          span = t("user_menu.edit_profile")
      li
        = link_to sign_out_path, method: :delete do
          i.fa.fa-sign-out
          span = t('user_menu.sign_out')

    - if current_user&.admin?
      ul.main-links
        li.divider
        li
          a(href='/admin')
            i.fa.fa-lock
            span Admin Panel

app/views/application/_header.html.slim
tour(step="currentStep")
  header class="global-header #{'is-homepage' unless signed_in?}" headroom="" tolerance="5" offset="20"
    div class="header-top"
      - unless params[:controller] == 'pages' && params[:id] == 'pricing'
        = link_to root_path, title: 'Kinscape', class: 'logo' do
          = image_tag('logo-large.svg')

        - unless signed_in?
          .brand-text
            = t("home.brand_text").html_safe

      - if signed_in?
        = render "header_menu"
      / - elsif params[:controller] == "sessions"
      /   = link_to sign_up_path, class: 'sign-in-button' do
      /     = t('sessions.form.sign_up')
      /     = image_tag 'homepage/arrow.svg', class: 'icon'
      - elsif params[:controller] == "families/invitations" && params[:action] == "show"
      / -else
      /   = link_to sign_in_path, class: 'sign-in-button' do
      /     = t('sessions.new.title')
      /     = image_tag 'homepage/arrow.svg', class: 'icon'

      = yield :submenu

app/views/application/_header_menu.html.slim
= active_link_to t('header.families'),
  families_path,
  class: 'nav-link',
  active: /communities/,
  title: t('header.families_title')

= active_link_to t('header.stories'),
  stories_path,
  class: "nav-link",
  title: t('header.stories_title')

= active_link_to t('header.mylife'),
  mylife_profile_path,
  class: "nav-link",
  active: /mylife/,
  title: t('header.mylife_title')

div.header-divider

= yield :menu
- if false #Temp. remove payment feature
  - unless current_user.active?
    = link_to new_billing_card_path, class: 'nav-button upgrade-subscription', title: t('subscriptions.upgrade_title') do
      - if current_user.guest?
        = t('subscriptions.upgrade')
      - else
        = t('subscriptions.upgrade_with_trial_days', day: current_user.subscription&.trial_days)

.flash-message
  flash-message

app/views/application/_intercom_widget.html.slim
- if signed_in?
  .intercom-widget#Intercom
    .word= t("application.intercom_widget.help")
  = raw(intercom_script_tag_for_current_user)